### ISSUE TITLE
Objective

### ISSUE THREAD

**Issue by fyhao** [fyhao/SpringBlockchainMonit#1]
Create spring boot based react websocket etherscan monitor app deployable to Heroku.

- [x] Complete initial MVP (Minimum Viable Product) Task
  - Spring boot react based
  - Websocket based dashboard 
  - Etherscan ERC20 Price change tracker real time push to websocket based dashboard
  - Websocket API client (browser/nodejs) with authentication token to access ERC20 Price Change Tracker
  - Unit Test in Java and React integrated with Github actions, enable dependabot in Github
  - Local JSON list for selected ERC20 tokens.

Main sub objectives:
- [ ] Internationalization, locale file, language switcher in React UI https://github.com/fyhao/SpringBlockchainMonit/issues/4
- [ ] Heroku cloud deployment https://github.com/fyhao/SpringBlockchainMonit/issues/5
- [ ] Docker repo #6
- [ ] iOS widget #7
- [ ] iOS jsbox wf #8

- Future development
  - k8s deployment
  - aws cdk deployment
